#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Accepts 4 parameters
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# The username scp connects with
# The path to the SSH private key that scp uses

SCP_OPTIONS="-o StrictHostKeyChecking=no"

if [ $# -ge 4 ]
then
  scp "$SCP_OPTIONS" -i "$4" "$1" "$3@$2":~/
else
  echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
