#!/usr/bin/env bash
# Script to manage my process
start()
{
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
}

stop()
{
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
}

restart()
{
	stop
	start
}

if [ $# -ne 1 ]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi

case "$1" in
	start)
		start
		echo "manage_my_process started"
		;;
	stop)
		stop
		echo "manage_my_process stopped"
		;;
	restart)
		restart
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit
esac
