#!/usr/bin/env bash
#kills the infinity and beyond program signal
#get the pid of the programe

id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)
#terminate the infinite process
if [ -n "sid" ]
then
kill -1S "$id"
fi
