#!/usr/bin/env bash
# bash script that configures ufw

#update stack
sudo apt-get -y  update

#install ufw
sudo apt-get -y install ufw

#traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing

#allow hosts
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp 

#enablw ufw
sudo ufw enable
